name: Gatsby Publish

on:
    push:
        branches:
            - final

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: enriikke/gatsby-gh-pages-action@v2
              with:
                  access-token: ${{ secrets.mizu }}
                  deploy-branch: gh-pages
